CREATE DATABASE YetiCave;
USE YetiCave;

CREATE TABLE categories (id INT AUTO_INCREMENT PRIMARY KEY, category CHAR(50), css_class CHAR(15) NOT NULL,
LotsId INT NOT NULL REFERENCES lots(id), INDEX(category));

CREATE TABLE lots (id INT AUTO_INCREMENT PRIMARY KEY, title CHAR(100) NOT NULL,
description CHAR(200), image TEXT NOT NULL, starting_price INTEGER NOT NULL,
date_of_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
date_of_completion DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, betting_step INTEGER NOT NULL,
winner CHAR(50) UNIQUE NOT NULL, UsersId INT NOT NULL REFERENCES users (id), INDEX (title, description,
starting_price, date_of_creation, date_of_completion, betting_step));

CREATE TABLE bets (id INT AUTO_INCREMENT PRIMARY KEY, date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
sum INTEGER NOT NULL, UsersId INT NOT NULL REFERENCES users (id), LotsId INT NOT NULL REFERENCES lots(id),
INDEX(sum));

CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, register_date DATETIME DEFAULT CURRENT_TIMESTAMP
NOT NULL, email CHAR(25) UNIQUE NOT NULL, author CHAR(50) UNIQUE NOT NULL, password CHAR(10) NOT NULL,
avatar TEXT, contacts CHAR(100) NOT NULL, INDEX(register_date));


